version: '3.3'
services:
  db:
    image: postgres
    ports:
      - "5450:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "${PG_DB_NAME}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
      - postgres-data-12:/var/lib/postgresql/data
volumes:
  postgres-data-12:
